### ISSUE TITLE
Data type

### ISSUE THREAD

**Issue by Pikachu1412** [wzsh/wmma_tensorcore_sample#2]
I wonder why it doesn't support int and unsigned char?
I compile with `nvcc -arch=sm_70 test.cu -o test`

**Comment by wzsh** [comment]
> I wonder why it doesn't support int and unsigned char?
> I compile with `nvcc -arch=sm_70 test.cu -o test`

Sorry, I'm not sure I understand your question.
Plz post your code and error message here.
